apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: config-service

resources:
  - configmap.yaml
  - migration-job.yaml
  - config-service-deployment.yaml
  - config-service-service.yaml
